#### Pandas-DataFrame And Series
Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A Series is a one-dimensional array-like object, while a DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

In [3]:
import pandas as pd

In [4]:
## Series
##A Pandas Series is a one-dimensional array-like object that can hold any data type. It is similar to a column in a table.
data = [1, 2, 3, 4, 5]
series = pd.Series(data)
print("Series \n", series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [5]:
## Create a series from dictionary
data = {"a": 1, "b": 2, "c": 3}
series_dir = pd.Series(data)
print(series_dir)

a    1
b    2
c    3
dtype: int64

In [6]:
data = [10,20,30]
index = ['a','b','c']
pd.Series(data,index)

a    10
b    20
c    30
dtype: int64

In [15]:
## Dataframe
## create a dataframe from a dictionary of list
data = {
    "Name": ["Krish", "John", "Jack"],
    "Age": [25, 30, 45],
    "City": ["Bangalore", "New York", "Chicago"],
}

df = pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   45    Chicago
<class 'pandas.DataFrame'>

In [8]:
import numpy as np
np.array(df)

array([['Krish', 25, 'Bangalore'],
       ['John', 30, 'New York'],
       ['Jack', 45, 'Chicago']], dtype=object)

In [9]:
## create a data from from a list of dictionaries
data = [
    {"Name": "Krish", "Age": 32, "City": "Bangalore"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Jack", "Age": 45, "City": "Chicago"},
]
df = pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age       City
0  Krish   32  Bangalore
1   John   30   New York
2   Jack   45    Chicago
<class 'pandas.DataFrame'>

In [10]:
df = pd.read_csv('sales_data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [11]:
df.tail(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [12]:
### Access data from dataframe
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [16]:
df['Name']

0    Krish
1     John
2     Jack
Name: Name, dtype: str

In [17]:
df.loc[0] # get the row index

Name        Krish
Age            25
City    Bangalore
Name: 0, dtype: object

In [18]:
df.iloc[0]  # get the column index

Name        Krish
Age            25
City    Bangalore
Name: 0, dtype: object

In [19]:
## Accessing a specified element
df['Name']

0    Krish
1     John
2     Jack
Name: Name, dtype: str

In [21]:
df

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   45    Chicago

In [25]:
df.at[2,'Age']

np.int64(45)

In [26]:
df.at[2,'Name']

'Jack'

In [28]:
## Accessing a specified element using iat
df.iat[2,2]

'Chicago'

In [29]:
### Data manipulation with dataframes
df

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   45    Chicago

In [31]:
df['Salary']=[50000,60000,70000]
df

    Name  Age       City  Salary
0  Krish   25  Bangalore   50000
1   John   30   New York   60000
2   Jack   45    Chicago   70000

In [37]:
## Remove a column
df.drop('Salary',axis=1,inplace=True)

In [38]:
df

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   45    Chicago

In [40]:
## Add age to the column
df["Age"] = df["Age"] + 1
df

    Name  Age       City
0  Krish   27  Bangalore
1   John   32   New York
2   Jack   47    Chicago

In [44]:
df.drop(0,inplace=True)

In [45]:
df

   Name  Age      City
1  John   32  New York
2  Jack   47   Chicago

In [47]:
df = pd.read_csv("sales_data.csv")
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [48]:
# Display the data types of each column
print("Data types:\n", df.dtypes)

# Describe the DataFrame
print("Statistical summary:\n", df.describe())

Data types:
 Transaction ID        int64
Date                    str
Product Category        str
Product Name            str
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region                  str
Payment Method          str
dtype: object
Statistical summary:
        Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [49]:
df.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000